[package]
name = "metrics_cloudwatch"
version = "0.8.3-alpha.0"
authors = ["ramn <github@rymdimperiet.org>"]
edition = "2018"

description = "CloudWatch emitter for the metrics crate"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/metrics_cloudwatch"
homepage = "https://github.com/ramn/metrics_cloudwatch"
repository = "https://github.com/ramn/metrics_cloudwatch"
readme = "README.md"
keywords = ["metrics", "cloudwatch", "aws"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"
futures = "0.3.5"
log = "0.4.11"
metrics = { version = "0.12.1", features = ["std"] }
rand = { version = "0.7", default-features = false, features = ["small_rng"] }
rusoto_cloudwatch = "0.45"
rusoto_core = "0.45"
serde_json = "1"
stream-cancel = "0.6.1"
tokio = { version = "0.2.21", features = ["full"] }

[dev-dependencies]
proptest = "0.10"
async-trait = "0.1.24"
criterion = "0.3"
tokio = { version = "0.2.21", features = ["full", "test-util"] }


[[bench]]
name = "bench"
harness = false
