[package]
name = "metrics_cloudwatch"
version = "0.13.0"
authors = ["ramn <github@rymdimperiet.org>"]
edition = "2018"

description = "CloudWatch emitter for the metrics crate"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/metrics_cloudwatch"
homepage = "https://github.com/ramn/metrics_cloudwatch"
repository = "https://github.com/ramn/metrics_cloudwatch"
readme = "README.md"
keywords = ["metrics", "cloudwatch", "aws"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"
futures-util = { version = "0.3.5", default-features = false }
log = "0.4.11"
metrics = { version = "0.15", features = ["std"] }
ordered-float = "2"
rand = { version = "0.8", default-features = false, features = ["small_rng", "std"] }
rusoto_cloudwatch = { version = "0.46", default-features = false }
rusoto_core = { version = "0.46", default-features = false }
serde_json = "1"
tokio = { version = "1", features = ["sync", "time"] }

[dev-dependencies]
proptest = "1"
async-trait = "0.1.24"
criterion = "0.3"
tokio = { version = "1", features = ["test-util"] }

[features]
default = ["native-tls"]
native-tls = ["rusoto_core/native-tls"]
rustls = ["rusoto_core/rustls"]

[[bench]]
name = "bench"
harness = false
