name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # All features except integration-test as we haven't setup an AWS account on github CI for those to work
      FEATURES: "gzip"
      RUST_LOG: "trace"

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Lint
        run: cargo fmt -- --check && ./clippy.sh
      - name: Test
        run: cargo test --all-targets --features "${FEATURES}"
      - name: Check no-default-features
        run: cargo check --all-targets --no-default-features
